# Generated by Django 2.2.7 on 2019-11-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Client')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Customer')),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Client')),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('appointment_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Client')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Client')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookappointment.Customer')),
            ],
        ),
    ]
