# Generated by Django 2.2.7 on 2019-11-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIstings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iungouser',
            name='client_category',
            field=models.CharField(default='arc', max_length=30),
            preserve_default=False,
        ),
    ]
