# Generated by Django 2.2.7 on 2019-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIstings', '0003_architects_architects_interiordesigners_contractors_interiordsigners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iungouser',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='iungouser',
            name='client_type',
            field=models.CharField(choices=[('Architects', 'Architects'), ('InteriorDsigners', 'InteriorDesigners'), ('Architects_InteriorDesigners', 'Architercts_InteriorDesigners'), ('Contractors', 'Contractors')], max_length=30),
        ),
    ]
