# Generated by Django 2.2.7 on 2019-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIstings', '0004_auto_20191117_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='iungouser',
            name='profile_image',
            field=models.ImageField(default='', upload_to='media/profile_images/'),
            preserve_default=False,
        ),
    ]
