# Generated by Django 2.2.7 on 2019-11-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LIstings', '0005_iungouser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iungouser',
            name='profile_image',
        ),
    ]
