# Generated by Django 2.2.7 on 2019-11-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIstings', '0006_remove_iungouser_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Architects',
        ),
        migrations.DeleteModel(
            name='Architects_InteriorDesigners',
        ),
        migrations.DeleteModel(
            name='Contractors',
        ),
        migrations.DeleteModel(
            name='InteriorDsigners',
        ),
        migrations.RemoveField(
            model_name='iungouser',
            name='client_category',
        ),
        migrations.RemoveField(
            model_name='iungouser',
            name='client_type',
        ),
        migrations.AddField(
            model_name='iungouser',
            name='ClientType',
            field=models.CharField(choices=[('Arch', 'Architects'), ('IntDes', 'InteriorDesiginers'), ('ArchInte', 'Architercts_InteriorDesigners'), ('Contr', 'Contractors')], default='', max_length=30),
            preserve_default=False,
        ),
    ]
