# Generated by Django 2.2.7 on 2019-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIstings', '0008_architects_architects_interiordesigenrs_contractors_interiordesigenrs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InteriorDesigenrs',
            new_name='InteriorDesigners',
        ),
        migrations.AlterField(
            model_name='iungouser',
            name='ClientType',
            field=models.CharField(choices=[('Architects', 'Architects'), ('InteriorDesigners', 'InteriorDesigners'), ('Architects_interiordesigenrs', 'Architects_interiordesigenrs'), ('Contractors', 'Contractors')], max_length=30),
        ),
    ]
