# Generated by Django 2.2.7 on 2019-11-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIstings', '0009_auto_20191124_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='iungouser',
            name='client_category',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
